### ISSUE TITLE
eUSD支付完成页面

### ISSUE THREAD

**Issue by wangxin1919** [mcdexio/idea#15]
EUSD支付端页面对接修改完成
https://www.figma.com/file/biAugPfmeKgdXr3LO4LaVC/eUSD%E4%B8%BB%E9%A1%B5%E9%9D%A2?node-id=0%3A1

**Comment by victor-crypto** [comment]
web h5 版本手机文案统一ing······

**Comment by victor-crypto** [comment]
感觉有精简的空间 周一完成

**Comment by victor-crypto** [comment]
## 描述:
和研发远程沟通
## 时间
预计开始:2020-09-01 16:30
预计结束:未知
