### ISSUE TITLE
Zendesk添加公告Category

### ISSUE THREAD

**Issue by victor-crypto** [mcdexio/idea#19]
描述：

- [x] Zendesk添加对应的Category用于发布公告（目前公告种类仅有永续合约，后续将随着任务的添加而添加 @victor-crypto 
- [x] UI在Footer上进行修改 @riverza 
- [x] 前端新增代码 @huhan-mcarlo

**Comment by victor-crypto** [comment]
- Zendesk已设置完成，当前因无文章（Draft张状态），系统自动隐藏，等publish后将自动显示

**Comment by riverza** [comment]
UI已设计完成

**Comment by huhan-mcarlo** [comment]
已经完成前端上线
