### ISSUE TITLE
添加eUSD在Figma上的动效流程以及补齐缺失页面

### ISSUE THREAD

**Issue by victor-crypto** [mcdexio/idea#39]
父任务 #15 
## 描述:
添加eUSD在Figma上的动效流程以及补齐缺失页面,方便南京协助人员开展代码工作
## 时间
预计开始:2020-09-01
预计结束:2020-09-02
## 步骤:

1. - [ ] eUSD在Figma上的动效流程 @victor-crypto 
2. - [ ] 文案修改 @victor-crypto 
3. - [x] 页面补齐 @wangxin1919 找 @riverza 要
    1. Mint调取钱包后成功/失败页面
   ![suiakX](http://victor-oss.oss-cn-shanghai.aliyuncs.com/uPic/suiakX.png)
    2. Reddem调取钱包后成功/失败页面
    3. Metamask钱包授权页面 
    ![yXhU7k](http://victor-oss.oss-cn-shanghai.aliyuncs.com/uPic/yXhU7k.png)

**Comment by victor-crypto** [comment]
## 描述
与 @riverza  核对最终文案
## 时间
2020-09-10

**Comment by riverza** [comment]
eusd弹窗流程以及文案核对完成
